spring.application.name=mcp-client
server.port=8066
spring.ai.mcp.client.sse.connections.javaServer.url=http://localhost:8989
spring.ai.mcp.client.sse.connections.javaServer.sse-endpoint=/sse
spring.ai.openai.chat.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${OPENAI_GROQ_KEY}
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.temperature=0.5
