spring.application.name=mcp-server-java
server.port=8989
spring.ai.mcp.server.name=javaServer03
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.version=1.0.0